# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_wiSIB(object):
    def setupUi(self, wiSIB):
        wiSIB.setObjectName("wiSIB")
        wiSIB.resize(1055, 412)
        wiSIB.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget = QtWidgets.QTabWidget(wiSIB)
        self.tabWidget.setGeometry(QtCore.QRect(20, 10, 311, 341))
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideRight)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.frame_3 = QtWidgets.QFrame(self.tab_1)
        self.frame_3.setGeometry(QtCore.QRect(10, 0, 441, 361))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.formLayoutWidget = QtWidgets.QWidget(self.frame_3)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 261, 58))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setVerticalSpacing(0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label)
        self.sys_in_win = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.sys_in_win.setEnabled(True)
        self.sys_in_win.setTabletTracking(False)
        self.sys_in_win.setText("")
        self.sys_in_win.setMaxLength(32782)
        self.sys_in_win.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.sys_in_win.setObjectName("sys_in_win")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.sys_in_win)
        self.sys_brw_btn = QtWidgets.QPushButton(self.formLayoutWidget)
        self.sys_brw_btn.setObjectName("sys_brw_btn")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.sys_brw_btn)
        self.tab_info_1 = QtWidgets.QTextBrowser(self.frame_3)
        self.tab_info_1.setGeometry(QtCore.QRect(10, 150, 261, 71))
        self.tab_info_1.setObjectName("tab_info_1")
        self.formLayoutWidget_4 = QtWidgets.QWidget(self.frame_3)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(10, 80, 261, 58))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setVerticalSpacing(0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_4.setObjectName("label_4")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_4)
        self.dam_in_win = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.dam_in_win.setEnabled(True)
        self.dam_in_win.setTabletTracking(False)
        self.dam_in_win.setText("")
        self.dam_in_win.setMaxLength(32782)
        self.dam_in_win.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.dam_in_win.setObjectName("dam_in_win")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.dam_in_win)
        self.dam_brw_btn = QtWidgets.QPushButton(self.formLayoutWidget_4)
        self.dam_brw_btn.setObjectName("dam_brw_btn")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.dam_brw_btn)
        self.sys_imp_btn = QtWidgets.QPushButton(self.frame_3)
        self.sys_imp_btn.setGeometry(QtCore.QRect(10, 230, 101, 20))
        self.sys_imp_btn.setObjectName("sys_imp_btn")
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.frame_4 = QtWidgets.QFrame(self.tab_2)
        self.frame_4.setGeometry(QtCore.QRect(10, 0, 441, 361))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.frame_4)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 261, 58))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setVerticalSpacing(0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_2)
        self.para_in_win = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.para_in_win.setEnabled(True)
        self.para_in_win.setTabletTracking(False)
        self.para_in_win.setText("")
        self.para_in_win.setMaxLength(32782)
        self.para_in_win.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.para_in_win.setObjectName("para_in_win")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.para_in_win)
        self.para_brw_btn = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.para_brw_btn.setObjectName("para_brw_btn")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.para_brw_btn)
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.frame_4)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(10, 80, 261, 58))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setVerticalSpacing(0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_3.setObjectName("label_3")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_3)
        self.load_in_win = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.load_in_win.setEnabled(True)
        self.load_in_win.setTabletTracking(False)
        self.load_in_win.setText("")
        self.load_in_win.setMaxLength(32782)
        self.load_in_win.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.load_in_win.setObjectName("load_in_win")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.load_in_win)
        self.load_brw_btn = QtWidgets.QPushButton(self.formLayoutWidget_3)
        self.load_brw_btn.setObjectName("load_brw_btn")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.load_brw_btn)
        self.tab_info_2 = QtWidgets.QTextBrowser(self.frame_4)
        self.tab_info_2.setGeometry(QtCore.QRect(10, 150, 261, 71))
        self.tab_info_2.setObjectName("tab_info_2")
        self.idf_imp_btn = QtWidgets.QPushButton(self.frame_4)
        self.idf_imp_btn.setGeometry(QtCore.QRect(10, 230, 101, 21))
        self.idf_imp_btn.setObjectName("idf_imp_btn")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.frame_5 = QtWidgets.QFrame(self.tab)
        self.frame_5.setGeometry(QtCore.QRect(10, 0, 281, 151))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.formLayoutWidget_5 = QtWidgets.QWidget(self.frame_5)
        self.formLayoutWidget_5.setGeometry(QtCore.QRect(10, 10, 261, 41))
        self.formLayoutWidget_5.setObjectName("formLayoutWidget_5")
        self.formLayout_5 = QtWidgets.QFormLayout(self.formLayoutWidget_5)
        self.formLayout_5.setContentsMargins(0, 0, 0, 0)
        self.formLayout_5.setVerticalSpacing(0)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_5.setObjectName("label_5")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.sim_get_btn = QtWidgets.QPushButton(self.formLayoutWidget_5)
        self.sim_get_btn.setObjectName("sim_get_btn")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.sim_get_btn)
        self.formLayoutWidget_6 = QtWidgets.QWidget(self.frame_5)
        self.formLayoutWidget_6.setGeometry(QtCore.QRect(10, 60, 261, 41))
        self.formLayoutWidget_6.setObjectName("formLayoutWidget_6")
        self.formLayout_6 = QtWidgets.QFormLayout(self.formLayoutWidget_6)
        self.formLayout_6.setContentsMargins(0, 0, 0, 0)
        self.formLayout_6.setVerticalSpacing(0)
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget_6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_6.setObjectName("label_6")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_6)
        self.mon_get_btn = QtWidgets.QPushButton(self.formLayoutWidget_6)
        self.mon_get_btn.setObjectName("mon_get_btn")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.mon_get_btn)
        self.columnView_3 = QtWidgets.QColumnView(self.frame_5)
        self.columnView_3.setGeometry(QtCore.QRect(0, 270, 491, 31))
        self.columnView_3.setObjectName("columnView_3")
        self.formLayoutWidget_7 = QtWidgets.QWidget(self.frame_5)
        self.formLayoutWidget_7.setGeometry(QtCore.QRect(10, 110, 261, 41))
        self.formLayoutWidget_7.setObjectName("formLayoutWidget_7")
        self.formLayout_7 = QtWidgets.QFormLayout(self.formLayoutWidget_7)
        self.formLayout_7.setContentsMargins(0, 0, 0, 0)
        self.formLayout_7.setVerticalSpacing(0)
        self.formLayout_7.setObjectName("formLayout_7")
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget_7)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_7.setObjectName("label_7")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_7)
        self.sys_idt_btn = QtWidgets.QPushButton(self.formLayoutWidget_7)
        self.sys_idt_btn.setObjectName("sys_idt_btn")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.sys_idt_btn)
        self.tab_info_3 = QtWidgets.QTextBrowser(self.tab)
        self.tab_info_3.setGeometry(QtCore.QRect(20, 160, 261, 81))
        self.tab_info_3.setObjectName("tab_info_3")
        self.bt_plot_btn = QtWidgets.QPushButton(self.tab)
        self.bt_plot_btn.setGeometry(QtCore.QRect(180, 250, 101, 21))
        self.bt_plot_btn.setObjectName("bt_plot_btn")
        self.tabWidget.addTab(self.tab, "")
        self.tabWidget_view = QtWidgets.QTabWidget(wiSIB)
        self.tabWidget_view.setGeometry(QtCore.QRect(340, 10, 691, 381))
        self.tabWidget_view.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget_view.setObjectName("tabWidget_view")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.Viewer1 = QtWebEngineWidgets.QWebEngineView(self.tab_3)
        self.Viewer1.setGeometry(QtCore.QRect(-60, 0, 751, 361))
        self.Viewer1.setUrl(QtCore.QUrl("about:blank"))
        self.Viewer1.setObjectName("Viewer1")
        self.tabWidget_view.addTab(self.tab_3, "")
        # self.tab_4 = QtWidgets.QWidget()
        # self.tab_4.setObjectName("tab_4")
        # self.Viewer2 = QtWebEngineWidgets.QWebEngineView(self.tab_4)
        # self.Viewer2.setGeometry(QtCore.QRect(0, 0, 691, 361))
        # self.Viewer2.setUrl(QtCore.QUrl("about:blank"))
        # self.Viewer2.setObjectName("Viewer2")
        # self.tabWidget_view.addTab(self.tab_4, "")
        # self.tab_5 = QtWidgets.QWidget()
        # self.tab_5.setObjectName("tab_5")
        # self.Viewer3 = QtWebEngineWidgets.QWebEngineView(self.tab_5)
        # self.Viewer3.setGeometry(QtCore.QRect(0, 0, 691, 361))
        # self.Viewer3.setUrl(QtCore.QUrl("about:blank"))
        # self.Viewer3.setObjectName("Viewer3")
        # self.tabWidget_view.addTab(self.tab_5, "")
        self.closeBtn = QtWidgets.QPushButton(wiSIB)
        self.closeBtn.setGeometry(QtCore.QRect(210, 370, 101, 21))
        self.closeBtn.setObjectName("closeBtn")

        self.retranslateUi(wiSIB)
        self.tabWidget.setCurrentIndex(2)
        self.tabWidget_view.setCurrentIndex(2)
        self.closeBtn.clicked.connect(wiSIB.close)
        QtCore.QMetaObject.connectSlotsByName(wiSIB)

    def retranslateUi(self, wiSIB):
        _translate = QtCore.QCoreApplication.translate
        wiSIB.setWindowTitle(_translate("wiSIB", "Dialog"))
        self.label.setText(_translate("wiSIB", "Import the origial system"))
        self.sys_brw_btn.setText(_translate("wiSIB", "browse"))
        self.label_4.setText(_translate("wiSIB", "Import the damage data"))
        self.dam_brw_btn.setText(_translate("wiSIB", "browse"))
        self.sys_imp_btn.setText(_translate("wiSIB", "import"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("wiSIB", "System"))
        self.label_2.setText(_translate("wiSIB", "Import parameter variants due to damage"))
        self.para_brw_btn.setText(_translate("wiSIB", "browse"))
        self.label_3.setText(_translate("wiSIB", "Import the monitoring data"))
        self.load_brw_btn.setText(_translate("wiSIB", "browse"))
        self.idf_imp_btn.setText(_translate("wiSIB", "import"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("wiSIB", "Variation"))
        self.label_5.setText(_translate("wiSIB", "Fetch simulation results at monitoring points"))
        self.sim_get_btn.setText(_translate("wiSIB", "execute"))
        self.label_6.setText(_translate("wiSIB", "Load monitoring data"))
        self.mon_get_btn.setText(_translate("wiSIB", "execute"))
        self.label_7.setText(_translate("wiSIB", "Search for the best-fits"))
        self.sys_idt_btn.setText(_translate("wiSIB", "execute"))
        self.bt_plot_btn.setText(_translate("wiSIB", "plot data"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("wiSIB", "Identification"))
        self.tabWidget_view.setTabText(self.tabWidget_view.indexOf(self.tab_3), _translate("wiSIB", "Show system"))
        # self.tabWidget_view.setTabText(self.tabWidget_view.indexOf(self.tab_4), _translate("wiSIB", "Show Data"))
        # self.tabWidget_view.setTabText(self.tabWidget_view.indexOf(self.tab_5), _translate("wiSIB", "Show sum"))
        self.closeBtn.setText(_translate("wiSIB", "close"))

from PyQt5 import QtWebEngineWidgets
